### ISSUE TITLE
Test convolutional layers

### ISSUE THREAD

**Issue by raspstephan** [raspstephan/CBRAIN-Keras-Diagnostics#5]
This is essentially @gentine 's idea: Instead of using fully connected networks, could we use convolutions in the vertical to improve the generalizability.

I already have a basic framework for convolutions but it should be tested more rigorously. To test the generalizability, I would suggest starting offline: Train the network with the reference climate and then test its predictions for a validation dataset with +1-4K.

**Comment by gentine** [comment]
Hi stephan
Thanks a lot. This is really cool. I think we should use a 2D convolution to include T and q (or RH) as covarying variable along with vertical information. That way the NN can discover energy conservation. We should allow reduction in skill score compared to the deep NN if indeed it can improve generality. 

Pierre Gentine
Associate Professor
Columbia University
www.gentine.com
